- name: Chuck Norris sample
  hosts: all
  tasks:
    - name: Everyone loves a good Chuck Norris joke
      uri:
        url: https://api.chucknorris.io/jokes/random
        method: GET
      register: results
    - debug: var=results.json.value
    - debug: var=network