- name: Chuck Norris sample
  hosts: all
  tasks:
    - name: Everyone loves a good Chuck Norris joke
      uri:
        url: https://api.chucknorris.io/jokes/random
        method: GET
      register: results
      when: nutanix_username=="ciccio"
    - debug: var=results.json.value
    - debug: var=nutanix_username